version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1.5.1
    ports:
      - '80:80'
      - '443:443'
    environment:
      restart: always
      STAGE: 'production'
      DOMAINS: 'localhost -> http://dockerhost:8000'
      WEBSOCKET: 'true'
    volumes:
      - https-portal:/var/lib/https-portal
volumes:
  https-portal:
