version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1.5.1
    ports:
      - '80:80'
      - '443:443'
    environment:
      STAGE: ${STAGE}
      DOMAINS: '${DOMAIN} -> http://dockerhost:${PORT}'
      WEBSOCKET: ${WEBSOCKET}
    volumes:
      - https-portal:/var/lib/https-portal
    restart: always
volumes:
  https-portal:
